use std::error::Error;

pub fn solve_first_star(input: &str) -> Result<String, Box<dyn Error>> {
    todo!()
}

pub fn solve_second_star(input: &str) -> Result<String, Box<dyn Error>> {
    todo!()
}
